### ISSUE TITLE
Update to work with GHC 8.6

### ISSUE THREAD

**Issue by denibertovic** [JustusAdam/marvin-interpolate#2]
Hey @JustusAdam 

On this line: https://github.com/JustusAdam/marvin-interpolate/blob/master/src/Marvin/Interpolate.hs#L107 we're not handling the empty list case.

I mentioned this to you earlier and it's because of this change: https://gitlab.haskell.org/ghc/ghc/wikis/migration/8.6#MonadFailDesugaringbydefault

Basically we need to handle the `[]` case and not just the `(name:rest)` case. 
This seems like a straightforward change except I'm not sure what we should do in `[]` case. If I just add `[] -> error "foo"` it compiles but it's not clear to me from the code what should really happen here. I've never worked with TH so the code is a bit of a mystery to me.

**Comment by denibertovic** [comment]
I should mention that if I just add the `error "foo"` case like above then `marvin` doesn't compile with the following error:

```

src/Marvin/Adapter/Telegram/Internal/Common.hs:429:35: error:
    • Exception when trying to run compile-time code:
        -2
SrcLoc "" -1 -1
Ambiguous infix expression

CallStack (from HasCallStack):
  error, called at src/Marvin/Interpolate.hs:102:30 in marvin-interpolate-1.1.2-7bUi0dx7DsZ62HIa5hRzJ3:Marvin.Interpolate
      Code: isT
              "Non 200 Response when downloading file: #{code} - #{fres^.responseStatus.statusMessage}"
    • In the untyped splice:
        $(isT
            "Non 200 Response when downloading file: #{code} - #{fres^.responseStatus.statusMessage}")
    |
429 |                         logErrorN $(isT "Non 200 Response when downloading file: #{code} - #{fres^.responseStatus.statusMessage}")
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This might *not* be related at all but it sure seems like it to me.

**Comment by denibertovic** [comment]
I'm happy to submit a PR but I'd appreciate some pointers if you have time to spare because I'm stuck.

**Comment by denibertovic** [comment]
Ok so for the above error about fixities.... I've found here: https://github.com/ennocramer/floskell/commits/master?after=545907f711c15e299ea63ec4fb1be2c05c8298c8+34
that we would have to define fixities for various lenses and so on. I've worked around this by using `view` instead of `^.`.

**Comment by JustusAdam** [comment]
I looked into it too and I think what might be cleaner here is just wrapping all user code in `()`?

**Comment by JustusAdam** [comment]
I pushed a small commit that should make the issue easier to debug. Please give it a shot
